name = "JuliaRegistry"
uuid = "502085bb-76c0-41d1-9bb3-128b9b543b7c"
repo = "https://github.com/nrontsis/JuliaRegistry.git"
description = "A registry for patched packages"

[packages]
30106799-4f9f-4b0d-bd7c-8755c9c83e81 = { name = "ComponentArrays", path = "C/ComponentArrays" }
